spring:
  security:
    oauth2:
      client:
        registration:
          github43:
            client-id: Ov23liJMQ7jFCGJRJcfT
            client-secret: f8384b7ccc05dd953e4c9ba5b589f3c0240b49da
            scope: repo
            redirect-uri: "{baseUrl}/github/code"
            authorization-grant-type: authorization_code
        provider:
          github43:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token